"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECRET_KEY: Sirve para cifrar datos sensibles como sesiones, tokens CSRF y cookies de autenticación, asegurando la seguridad de la aplicación.
SECRET_KEY = 'django-insecure-+fwh0flff1@i6pcdj!zl6-@1ce^!)o_u)#n*5pw^(=yf$_1)!$'

# DEBUG: Sirve para activar el modo de depuración, mostrando errores detallados y páginas de error útiles durante el desarrollo.
DEBUG = True

# ALLOWED_HOSTS: Sirve para especificar los hosts permitidos desde los que se pueden hacer solicitudes al servidor, previniendo ataques de host header.
ALLOWED_HOSTS = ['*']  # Para desarrollo


# Application definition

# INSTALLED_APPS: Sirve para listar todas las aplicaciones Django instaladas, permitiendo que el framework reconozca modelos, vistas y URLs de estas apps.
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',  # CORS para React
    'rest_framework',  # API REST
    'Backend.modelo',
]

# MIDDLEWARE: Sirve para definir una lista de clases middleware que procesan cada solicitud HTTP entrante y respuesta saliente, añadiendo funcionalidades como CORS, sesiones y seguridad.
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # Debe estar primero
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# ROOT_URLCONF: Sirve para especificar el módulo que contiene las configuraciones de URLs raíz del proyecto, donde se definen las rutas principales.
ROOT_URLCONF = 'Backend.config.urls'

# TEMPLATES: Sirve para configurar los motores de plantillas que Django usa para renderizar páginas HTML dinámicas.
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# WSGI_APPLICATION: Sirve para especificar la aplicación WSGI que se usa para desplegar el proyecto en servidores compatibles con WSGI.
WSGI_APPLICATION = 'Backend.config.wsgi.application'

# DATABASES: Sirve para configurar las bases de datos que usa el proyecto, definiendo el motor, nombre, usuario, contraseña y otros parámetros de conexión.
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'orientarso', 
        'USER': 'root',               
        'PASSWORD': '',               
        'HOST': '127.0.0.1',
        'PORT': '3306',
    }
}

# AUTH_PASSWORD_VALIDATORS: Sirve para definir validadores que verifican la fortaleza de las contraseñas de los usuarios durante el registro y cambios.
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# LANGUAGE_CODE: Sirve para establecer el idioma predeterminado de la aplicación.
# TIME_ZONE: Sirve para definir la zona horaria usada por el proyecto.
# USE_I18N: Sirve para activar la internacionalización, permitiendo traducciones.
# USE_TZ: Sirve para activar el manejo de zonas horarias en fechas y horas.
LANGUAGE_CODE = 'es-es'
TIME_ZONE = 'America/Bogota'
USE_I18N = True
USE_TZ = True

# STATIC_URL: Sirve para definir la URL base para servir archivos estáticos como CSS y JavaScript.
# STATIC_ROOT: Sirve para especificar el directorio donde se recopilan los archivos estáticos para producción.
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# MEDIA_URL: Sirve para definir la URL base para servir archivos multimedia subidos por usuarios.
# MEDIA_ROOT: Sirve para especificar el directorio donde se almacenan los archivos multimedia.
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# ==========================
# CONFIGURACIÓN DE SESIÓN
# ==========================

# SESSION_COOKIE_AGE: Sirve para definir la duración en segundos de las sesiones de usuario.
# SESSION_EXPIRE_AT_BROWSER_CLOSE: Sirve para determinar si la sesión expira al cerrar el navegador.
# SESSION_COOKIE_HTTPONLY: Sirve para prevenir acceso a la cookie de sesión desde JavaScript.
# SESSION_COOKIE_SECURE: Sirve para enviar la cookie solo sobre HTTPS.
# SESSION_COOKIE_SAMESITE: Sirve para controlar cuándo se envía la cookie en solicitudes cross-site.
SESSION_COOKIE_AGE = 3600
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = False
SESSION_COOKIE_SAMESITE = 'Lax'

# ELIMINADO: LOGIN_URL, LOGIN_REDIRECT_URL, LOGOUT_REDIRECT_URL 

# ==========================
# CONFIGURACIÓN DE CORS
# ==========================

# CORS_ALLOWED_ORIGINS: Sirve para listar los orígenes permitidos para solicitudes CORS desde el frontend.
# CORS_ALLOW_CREDENTIALS: Sirve para permitir el envío de credenciales (cookies, headers de autorización) en solicitudes CORS.
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",   # Vite (React)
    "http://localhost:3000",   # Alternativo
    "http://127.0.0.1:5173",
    "http://127.0.0.1:3000",
]

CORS_ALLOW_CREDENTIALS = True

# ==========================
# CSRF TRUSTED ORIGINS
# ==========================

# CSRF_TRUSTED_ORIGINS: Sirve para listar orígenes confiables para tokens CSRF, permitiendo solicitudes POST desde esos orígenes.
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",
    "http://localhost:3000",
    "http://127.0.0.1:5173",
    "http://127.0.0.1:3000",
]

# ==========================
# CONFIGURACIÓN REST FRAMEWORK
# ==========================

# REST_FRAMEWORK: Sirve para configurar Django REST Framework, definiendo clases de autenticación y permisos predeterminadas para las APIs.
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',  # Cambié a AllowAny para las APIs públicas
    ],
}